source $HOME/.config/nvim/plugs/plugins.vim
source $HOME/.config/nvim/modules/functions.vim
source $HOME/.config/nvim/modules/general.vim
source $HOME/.config/nvim/modules/coc.vim
source $HOME/.config/nvim/modules/nerdtree.vim
source $HOME/.config/nvim/modules/prettier.vim
source $HOME/.config/nvim/modules/ctrlp.vim
source $HOME/.config/nvim/modules/airline.vim
source $HOME/.config/nvim/modules/bufferline.vim
